services:
  postgres:
    image: postgres:16
    container_name: ai_news_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ai_news_user
      POSTGRES_PASSWORD: ai_news_password
      POSTGRES_DB: ai_news_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: